### ISSUE TITLE
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by nobodybut** [Tencent/HunyuanDiT#13]
尝试了修改为CPU模式下运行，能改的地方都改了，改到这里无处可改了，llava相关代码都已经默认指定了用CPU，但不知道为啥还是有问题……

Traceback (most recent call last):
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/gradio/blocks.py", line 1887, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/gradio/blocks.py", line 1472, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/gradio/utils.py", line 808, in wrapper
    response = f(*args, **kwargs)
  File "app/hydit_app.py", line 42, in infer
    success, enhanced_prompt = enhancer(prompt)
  File "/HunyuanDiT/./dialoggen/dialoggen_demo.py", line 146, in __call__
    enhanced_prompt = eval_model(
  File "/HunyuanDiT/./dialoggen/dialoggen_demo.py", line 114, in eval_model
    output_ids = models["model"].generate(
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/HunyuanDiT/dialoggen/llava/model/language_model/llava_mistral.py", line 125, in generate
    ) = self.prepare_inputs_labels_for_multimodal(
  File "/HunyuanDiT/dialoggen/llava/model/llava_arch.py", line 157, in prepare_inputs_labels_for_multimodal
    image_features = self.encode_images(concat_images)
  File "/HunyuanDiT/dialoggen/llava/model/llava_arch.py", line 141, in encode_images
    image_features = self.get_model().get_vision_tower()(images)
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/HunyuanDiT/dialoggen/llava/model/multimodal_encoder/clip_encoder.py", line 54, in forward
    image_forward_outs = self.vision_tower(images.to(device=self.device, dtype=self.dtype), output_hidden_states=True)
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 917, in forward
    return self.vision_model(
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 841, in forward
    hidden_states = self.embeddings(pixel_values)
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 182, in forward
    patch_embeds = self.patch_embedding(pixel_values.to(dtype=target_dtype))  # shape = [*, width, grid, grid]
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

**Comment by yestinl** [comment]
Currently, we do not support inference on CPU alone, and we welcome developers to join us in building this together.
