### ISSUE TITLE
There is an download error came out when in China

### ISSUE THREAD

**Issue by AIzealotwu** [Tencent/HunyuanDiT#141]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When I downloaded the model in China, an error show up
Traceback (most recent call last):███  | 5.10G/6.07G [45:43<14:52:03, 18.1kB/s]
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/urllib3/response.py", line 748, in _error_catcher
    yield
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/urllib3/response.py", line 873, in _raw_read
    data = self._fp_read(amt, read1=read1) if not fp_closed else b""
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/urllib3/response.py", line 856, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/urllib3/response.py", line 1060, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/urllib3/response.py", line 949, in read
    data = self._raw_read(amt)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/urllib3/response.py", line 902, in _raw_read
    self._fp.close()
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/urllib3/response.py", line 753, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.") from e  # type: ignore[arg-type]
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdn-lfs-us-1.hf-mirror.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 539, in http_get
    for chunk in r.iter_content(chunk_size=DOWNLOAD_CHUNK_SIZE):
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/requests/models.py", line 826, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs-us-1.hf-mirror.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/urllib3/response.py", line 748, in _error_catcher
    yield
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/urllib3/response.py", line 894, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(709376326 bytes read, 963687976 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/urllib3/response.py", line 1060, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/urllib3/response.py", line 977, in read
    data = self._raw_read(amt)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/urllib3/response.py", line 902, in _raw_read
    self._fp.close()
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/urllib3/response.py", line 772, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(709376326 bytes read, 963687976 more expected)', IncompleteRead(709376326 bytes read, 963687976 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xuym/miniconda3/envs/HunyuanDiT/bin/huggingface-cli", line 8, in <module>
    sys.exit(main())
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/huggingface_hub/commands/huggingface_cli.py", line 51, in main
    service.run()
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/huggingface_hub/commands/download.py", line 146, in run
    print(self._download())  # Print path to downloaded files
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/huggingface_hub/commands/download.py", line 180, in _download
    return snapshot_download(
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/huggingface_hub/_snapshot_download.py", line 294, in snapshot_download
    thread_map(
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/huggingface_hub/_snapshot_download.py", line 268, in _inner_hf_hub_download
    return hf_hub_download(
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1202, in hf_hub_download
    return _hf_hub_download_to_local_dir(
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1487, in _hf_hub_download_to_local_dir
    _download_to_tmp_and_move(
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1884, in _download_to_tmp_and_move
    http_get(
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 556, in http_get
    return http_get(
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 539, in http_get
    for chunk in r.iter_content(chunk_size=DOWNLOAD_CHUNK_SIZE):
  File "/home/xuym/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/requests/models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(709376326 bytes read, 963687976 more expected)', IncompleteRead(709376326 bytes read, 963687976 more expected))

**Reproduction**

1. What command or script did you run?
HF_ENDPOINT=https://hf-mirror.com huggingface-cli download Tencent-Hunyuan/HunyuanDiT --local-dir ./ckpts

Thanks for spending time reading my issue, hope you could fix this.

**Comment by AIzealotwu** [comment]
Maybe this problem could be solved by using modelscope or try many times with the huggingface resume function
