### ISSUE TITLE
DreamBoothSubset.__init__() missing 1 required positional argument: 'alpha_mask' error!!

### ISSUE THREAD

**Issue by ShoponSKP** [Tencent/HunyuanDiT#163]
03:29:50-183722 INFO     Start training LoRA LyCORIS/LoCon ...
03:29:50-184718 INFO     Validating lr scheduler arguments...
03:29:50-185716 INFO     Validating optimizer arguments...
03:29:50-187708 INFO     Validating G:/parquet/extracted\log existence and writability... SUCCESS
03:29:50-188705 INFO     Validating G:/parquet/extracted\model existence and writability... SUCCESS
03:29:50-189702 ERROR    Validating G:/kohya_ss/models/HunyuanDiT-V1.1-fp16-pruned existence... FAILED: does not exist
03:29:50-190698 INFO     Validating G:/kohya_ss/models/HunyuanDiT-V1.1-fp16-pruned existence... SUCCESS
03:29:50-191695 INFO     Validating G:/parquet/extracted\img existence... SUCCESS
03:29:50-193688 INFO     Folder 1_person portrait: 1 repeats found
03:29:50-194685 INFO     Folder 1_person portrait: 133 images found
03:29:50-195682 INFO     Folder 1_person portrait: 133 * 1 = 133 steps
03:29:50-196678 INFO     Regulatization factor: 1
03:29:50-196678 INFO     Total steps: 133
03:29:50-197675 INFO     Train batch size: 1
03:29:50-198672 INFO     Gradient accumulation steps: 1
03:29:50-199668 INFO     Epoch: 2
03:29:50-200665 INFO     Max train steps: 1600
03:29:50-201662 INFO     stop_text_encoder_training = 0
03:29:50-201662 INFO     lr_warmup_steps = 160
03:29:50-204653 INFO     Saving training config to G:/parquet/extracted\model\last_20240719-032950.json...
03:29:50-206687 INFO     Executing command: G:\kohya_ss\venv\Scripts\accelerate.EXE launch --dynamo_backend no
                         --dynamo_mode default --mixed_precision fp16 --num_processes 1 --num_machines 1
                         --num_cpu_threads_per_process 2 G:/kohya_ss/sd-scripts/hunyuan_train_network.py --config_file
                         G:/parquet/extracted\model/config_lora-20240719-032950.toml
03:29:50-210631 INFO     Command executed.
2024-07-19 03:29:59 INFO     Loading settings from                                                    train_util.py:3924
                             G:/parquet/extracted\model/config_lora-20240719-032950.toml...
                    INFO     G:/parquet/extracted\model/config_lora-20240719-032950                   train_util.py:3943
                    WARNING  v_parameterization should be with v2 not v1 or sdxl /                    train_util.py:3622
                             v1やsdxlでv_parameterizationを使用することは想定されていません
2024-07-19 03:30:01 INFO     Using DreamBooth method.                                               train_network.py:178
Traceback (most recent call last):
  File "G:\kohya_ss\sd-scripts\hunyuan_train_network.py", line 242, in <module>
    trainer.train(args)
  File "G:\kohya_ss\sd-scripts\train_network.py", line 204, in train
    train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
  File "G:\kohya_ss\sd-scripts\library\config_util.py", line 481, in generate_dataset_group_by_blueprint
    subsets = [subset_klass(**asdict(subset_blueprint.params)) for subset_blueprint in dataset_blueprint.subsets]
  File "G:\kohya_ss\sd-scripts\library\config_util.py", line 481, in <listcomp>
    subsets = [subset_klass(**asdict(subset_blueprint.params)) for subset_blueprint in dataset_blueprint.subsets]
TypeError: DreamBoothSubset.__init__() missing 1 required positional argument: 'alpha_mask'
Traceback (most recent call last):
  File "C:\Users\shopo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\shopo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "G:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "G:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "G:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['G:\\kohya_ss\\venv\\Scripts\\python.exe', 'G:/kohya_ss/sd-scripts/hunyuan_train_network.py', '--config_file', 'G:/parquet/extracted\\model/config_lora-20240719-032950.toml']' returned non-zero exit status 1.

getting this Error no matter what I do!! please some one help me fixing this...

**Comment by tangerdream** [comment]
程序员快来修一下呀。。。我也遇到了
