### ISSUE TITLE
ComfyUI failing to load comfyui-hydit 

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [Tencent/HunyuanDiT#173]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched for related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Running a ComfyUI with comfyui-hydit installed, and getting the error:
``` log
Traceback (most recent call last):
  File "/home/alexds9/Documents/stable_diffusion/ComfyUI/nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/alexds9/Documents/stable_diffusion/ComfyUI/custom_nodes/comfyui-hydit/__init__.py", line 1, in <module>
    from .nodes import *
  File "/home/alexds9/Documents/stable_diffusion/ComfyUI/custom_nodes/comfyui-hydit/nodes.py", line 7, in <module>
    from .hydit_v1_1.diffusion.pipeline import StableDiffusionPipeline
  File "/home/alexds9/Documents/stable_diffusion/ComfyUI/custom_nodes/comfyui-hydit/hydit_v1_1/diffusion/pipeline.py", line 35, in <module>
    from ..modules.models import HunYuanDiT
  File "/home/alexds9/Documents/stable_diffusion/ComfyUI/custom_nodes/comfyui-hydit/hydit_v1_1/modules/models.py", line 13, in <module>
    from transformers.integrations import PeftAdapterMixin
ImportError: cannot import name 'PeftAdapterMixin' from 'transformers.integrations' (/home/alexds9/Documents/stable_diffusion/ComfyUI/venv/lib/python3.10/site-packages/transformers/integrations.py)

0.6 seconds (IMPORT FAILED): /home/alexds9/Documents/stable_diffusion/ComfyUI/custom_nodes/comfyui-hydit
```
**Reproduction**

1. What command or script did you run?
I followed the instruction of ComfyUI installation, including:
`git reset --hard 90389b3b8a69c08c3ed0bcc9d87a92246578a8e3`

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No modificatons.
3. What dataset did you use?
No dataset.

**Environment**

1. Please run `python utils/collect_env.py` to collect necessary environment information and paste it here.
``` log
python utils/collect_env.py
sys.platform: linux
Python: 3.10.6 (main, Jul  8 2024, 18:43:36) [GCC 13.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 4060 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
GCC: gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2+cu117
OpenCV: 4.7.0
```

**Comment by zml-ai** [comment]
#188
