### ISSUE TITLE
AttributeError: 'CLIP' object has no attribute 'encode_from_tokens_scheduled'

### ISSUE THREAD

**Issue by FrankGonzalez07** [Tencent/HunyuanDiT#219]
Eng Version：
When using the custom_nodes comfyui-hydit, it show the following error:
Traceback (most recent call last): File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 323, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 198, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) File "/home/easyai/Projects/23_ComfyUI/ComfyUI/nodes.py", line 65, in encode return (clip.encode_from_tokens_scheduled(tokens), ) AttributeError: 'CLIP' object has no attribute 'encode_from_tokens_scheduled'

My env:
transformers==4.45.2
clip==0.2.0
diffusers==0.31.0

中文版：
调用comfyui时，会报错如下：
Traceback (most recent call last): File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 323, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 198, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "/home/easyai/Projects/23_ComfyUI/ComfyUI/execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) File "/home/easyai/Projects/23_ComfyUI/ComfyUI/nodes.py", line 65, in encode return (clip.encode_from_tokens_scheduled(tokens), ) AttributeError: 'CLIP' object has no attribute 'encode_from_tokens_scheduled'

环境参数：
transformers==4.45.2
clip==0.2.0
diffusers==0.31.0

**Comment by zml-ai** [comment]
Hi, you can now directly use the nodes provided by the Comfyui official. 
See details: https://github.com/comfyanonymous/ComfyUI.
See workflow: https://github.com/Tencent/HunyuanDiT/tree/main/comfyui.
Support for ControlNet and LoRA has been added.
