### ISSUE TITLE
我在colab中运行你们huggingface空间和给出的安装步骤也试了一遍，报错，另外你们这个有精简的版本吗？硬盘和内存我估计会占用很大

### ISSUE THREAD

**Issue by libai-lab** [Tencent/HunyuanDiT#24]
运行python app.py 报错
Fetching 39 files: 100% 39/39 [00:00<00:00, 40.28it/s]
Traceback (most recent call last):
  File "/content/HunyuanDiT/app.py", line 17, in <module>
    from sample_t2i import inferencer
  File "/content/HunyuanDiT/sample_t2i.py", line 5, in <module>
    from dialoggen.dialoggen_demo import DialogGen
  File "/content/HunyuanDiT/dialoggen/dialoggen_demo.py", line 9, in <module>
    from llava.constants import (
  File "/content/HunyuanDiT/dialoggen/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model' (/content/HunyuanDiT/dialoggen/llava/model/__init__.py)

**Comment by Jiangfeng-Xiong** [comment]
1. You can provide more environment information here using `utils/collect_env.py`
2. We will release a lightweight model in the near feature, please refer to #52
