### ISSUE TITLE
启动 multiTurnT2I_app.py，在UI中输入提示词，点击提交后，出现错误

### ISSUE THREAD

**Issue by yhqqxq** [Tencent/HunyuanDiT#54]
请问一下，如何解决？
input history:[]
Traceback (most recent call last):
  File "G:\AI\ZHB\HunyuanDiT\env\lib\site-packages\gradio\routes.py", line 534, in predict
    output = await route_utils.call_process_api(
  File "G:\AI\ZHB\HunyuanDiT\env\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "G:\AI\ZHB\HunyuanDiT\env\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "G:\AI\ZHB\HunyuanDiT\env\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\AI\ZHB\HunyuanDiT\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "G:\AI\ZHB\HunyuanDiT\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "G:\AI\ZHB\HunyuanDiT\env\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "G:\AI\ZHB\HunyuanDiT\env\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "G:\AI\ZHB\HunyuanDiT\app\multiTurnT2I_app.py", line 115, in pipeline
    response, history_messages = enhancer(input_text, return_history=True, history=history_messages, skip_special=False)

**Comment by yestinl** [comment]
@yhqqxq 能否看一下你的运行环境
> python utils/collect_env.py

**Comment by yhqqxq** [comment]
@yestinl 上面的就是完整的报错内容，就只有这些。
运行环境如下：
sys.platform: win32
Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3060
CUDA_HOME: D:\SystemTool\CUDA
NVCC: Cuda compilation tools, release 12.2, V12.2.140
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.39.33523 版
GCC: n/a
PyTorch: 2.1.0+cu121
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192930151
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.8.1  (built against CUDA 12.0)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.8.1, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /utf-8 /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.16.0+cu121

**Comment by yestinl** [comment]
@yhqqxq 你的环境是通过我们提供的脚本安装的吗？以及你的gradio版本是多少。这边建议用gradio==3.50.2

**Comment by yhqqxq** [comment]
@yestinl 是用你们的脚本安装的，gradio也没问题，hydit_app.py这个是可以正常使用的，multiTurnT2I_app.py就不行

**Comment by yestinl** [comment]
@yhqqxq 能提供你完整的运行脚本吗？包括hydit_app.py和multiTurnT2I_app.py的。
以及你的3060显卡显存多大？如果想使用multiTurnT2I_app至少要22G显存（指定4bit 量化的模式)，如果没有指定的话需要32g显存。顺便能否pip list 打印一下你安装包的版本。

**Comment by yhqqxq** [comment]
multiTurnT2I_app，使用这个必须要22G显存吗？我这边只有12G，如果是因为这个原因，那确实就没办法继续尝试了

**Comment by yestinl** [comment]
@yhqqxq 是的，现阶段至少22G显存。如果你想体验多轮绘图能力，也可以进入https://hunyuan.tencent.com/bot/chat中体验

**Comment by weiguang3100** [comment]
我的3090 24G也是报这个错误，To create a public link, set `share=True` in `launch()`.
input history:[]
Traceback (most recent call last):
  File "E:\wwg\work\allinone\HunyuanDiT\env\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "E:\wwg\work\allinone\HunyuanDiT\env\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\wwg\work\allinone\HunyuanDiT\env\lib\site-packages\gradio\blocks.py", line 1887, in process_api
    result = await self.call_function(
  File "E:\wwg\work\allinone\HunyuanDiT\env\lib\site-packages\gradio\blocks.py", line 1472, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\wwg\work\allinone\HunyuanDiT\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\wwg\work\allinone\HunyuanDiT\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "E:\wwg\work\allinone\HunyuanDiT\env\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "E:\wwg\work\allinone\HunyuanDiT\env\lib\site-packages\gradio\utils.py", line 808, in wrapper
    response = f(*args, **kwargs)
  File "E:\wwg\work\allinone\HunyuanDiT\app\multiTurnT2I_app.py", line 115, in pipeline
    response, history_messages = enhancer(input_text, return_history=True, history=history_messages, skip_special=False)
TypeError: DialogGen.__call__() got an unexpected keyword argument 'return_history'
启动脚本是 app/multiTurnT2I_app.py --load-4bit

**Comment by yestinl** [comment]
@weiguang3100 请问已经更新最新的代码了吗

**Comment by weiguang3100** [comment]
是的，之前fork的，git pull不行，我手动下载的

**Comment by weiguang3100** [comment]
@yestinl 可以了，我全部覆盖一下，可能是上次没覆盖完，我windows上跑的，可以运行了

**Comment by yestinl** [comment]
@weiguang3100 好的~希望我们的工作对你有帮助！

**Comment by weiguang3100** [comment]
多谢，很棒

**Comment by yhqqxq** [comment]
@yestinl 好的，明白了，感谢
