### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by songproducer** [Tencent/HunyuanDiT#81]
```
** Platform: Linux
** Python version: 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0]
** Python executable: /home/leo/miniconda3/envs/HunyuanDiT/bin/python
** Log path: /home/leo/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.1 seconds: /home/leo/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 24327 MB, total RAM 15838 MB
pytorch version: 2.0.1+cu117
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
### Loading: ComfyUI-Manager (V2.36)
### ComfyUI Revision: 2229 [6cd8ffc4] | Released on '2024-06-08'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
/home/leo/miniconda3/envs/HunyuanDiT/lib/python3.8/site-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
Traceback (most recent call last):
  File "/home/leo/ComfyUI/nodes.py", line 1881, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/leo/ComfyUI/custom_nodes/comfyui-hydit/__init__.py", line 1, in <module>
    from .nodes import *
  File "/home/leo/ComfyUI/custom_nodes/comfyui-hydit/nodes.py", line 4, in <module>
    from .utils import convert_images_to_tensors
  File "/home/leo/ComfyUI/custom_nodes/comfyui-hydit/utils.py", line 208, in <module>
    def convert_images_to_tensors(images: list[Image.Image]):
TypeError: 'type' object is not subscriptable

Cannot import /home/leo/ComfyUI/custom_nodes/comfyui-hydit module for custom nodes: 'type' object is not subscriptable
```

**Comment by xuhuaren** [comment]
--extra-index-url https://pypi.ngc.nvidia.com
--extra-index-url https://download.pytorch.org/whl/cu117
timm==1.0.3
diffusers==0.21.2
peft==0.10.0
protobuf==5.27.0
accelerate==0.30.1
loguru==0.7.2
sentencepiece==0.2.0
cuda-python==12.5.0
polygraphy==0.49.9
pandas==2.2.2
omegaconf==2.3.0
xformers==0.0.20
pytorch-lightning==2.2.5
please check the version of the package above, also can use pip install -r requirements.txt command.
