### ISSUE TITLE
comfyui-hydit全部依赖安装成功，启动ComfyUI报错“No module named 'diffusers.models.lora'”

### ISSUE THREAD

**Issue by petercham** [Tencent/HunyuanDiT#91]
requirements.txt，包括diffusers已经全部成功安装，但是运行ComfyUI的时候IMPORT FAILED。

具体报错如下：
Traceback (most recent call last):
  File "C:\Work\SD-ComfyUI\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\comfyui-hydit\__init__.py", line 1, in <module>
    from .nodes import *
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\comfyui-hydit\nodes.py", line 7, in <module>
    from .hydit.diffusion.pipeline import StableDiffusionPipeline
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\comfyui-hydit\hydit\diffusion\pipeline.py", line 24, in <module>
    from diffusers.models.lora import adjust_lora_scale_text_encoder
ModuleNotFoundError: No module named 'diffusers.models.lora'

是不是需要指定diffuser的版本？

**Comment by petercham** [comment]
pip uninstall diffusers
发现当前安装的是0.18.2版本，重新执行
pip install diffusers
安装的是0.29.0版本
重新启动ComfyUI，可以正确引用了，建议加上依赖的版本要求
